#! /bin/sh
# (c) Copyright 2019-2022, James Stevens ... see LICENSE for details
# Alternative license arrangements are possible, contact me for more information

me="$(cat list)"

docker image build -t ${me} $* .
